<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Mapster" Version="10.0.12" />
    <PackageReference Include="SixLabors.ImageSharp" Version="4.1.2" />
    <ProjectReference Include="..\Gym.DataAceess\Gym.DataAceess.csproj" />
  </ItemGroup>

</Project>
