<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Gym.BusinessLogic\Gym.BusinessLogic.csproj" />
    <ProjectReference Include="..\Gym.DataAceess\Gym.DataAceess.csproj" />
  </ItemGroup>

</Project>
